<a href="https://colab.research.google.com/github/Yaman-Shadid/Project-2/blob/main/Project_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project 2**

## Imports

In [ ]:
# import libraries
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
# Mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

First Choice: **Path of Exile Economy**

In [ ]:
# Save the filepath and load the data as df
fpath = "/content/drive/MyDrive/Colab Notebooks/PROJECT 2 [--]/path_of_exile_currency_hardcore_kalandra.csv"
df1 = pd.read_csv(fpath)
df1.head()

,League,Date,Get,Pay,Value,Confidence,Patch,Hardcore,Standard
0,Hardcore Kalandra,2022-08-19,Blacksmith's Whetstone,Chaos Orb,1.00000,Low,3.19,Yes,No
1,Hardcore Kalandra,2022-08-20,Blacksmith's Whetstone,Chaos Orb,0.09250,Medium,3.19,Yes,No
2,Hardcore Kalandra,2022-08-21,Blacksmith's Whetstone,Chaos Orb,0.07143,High,3.19,Yes,No
3,Hardcore Kalandra,2022-08-22,Blacksmith's Whetstone,Chaos Orb,0.03975,High,3.19,Yes,No
4,Hardcore Kalandra,2022-08-23,Blacksmith's Whetstone,Chaos Orb,0.03048,High,3.19,Yes,No

In [ ]:
# Get the shape of the dataset (rows, columns)
num_rows, num_columns = df1.shape

# Get the column names
column_names = df1.columns.tolist()

print("Number of features (columns):", num_columns)
print("Column names:", column_names)

Number of features (columns): 19
Column names: ['ID', 'AGE', 'GENDER', 'RACE', 'DRIVING_EXPERIENCE', 'EDUCATION', 'INCOME', 'CREDIT_SCORE', 'VEHICLE_OWNERSHIP', 'VEHICLE_YEAR', 'MARRIED', 'CHILDREN', 'POSTAL_CODE', 'ANNUAL_MILEAGE', 'VEHICLE_TYPE', 'SPEEDING_VIOLATIONS', 'DUIS', 'PAST_ACCIDENTS', 'OUTCOME']

In [ ]:
# Get the shape of the dataset (rows, columns)
num_rows, num_columns = df1.shape

print("Number of rows:", num_rows)

Number of rows: 10000

1. Source of data

[Kaggle](https://www.kaggle.com/datasets/ulrikthygepedersen/path-of-exile-currency-economy-of-an-online-game)
```
[Kaggle]
```


2. Brief description of data


```
This dataset contains the values of currencies in game.
The Chaos Orb is often used as a reference currency and the others are valued in amount of Chaos Orbs.
```


3. What is the target?


```
The target value for this dataset is likely to be the currency values.
Specifically the values of different currencies in terms of Chaos Orbs.
```


4. What does one row represent? (A person? A business? An event? A product?)


```
Each row in the dataset represents a daily snapshot of currency values within the game's economy.
```


5. Is this a classification or regression problem?


```
Regression problem
```


6. How many features does the data have?


```
19
```


7. How many rows are in the dataset?


```
10,000
```


8. What, if any, challenges do you foresee in cleaning, exploring, or modeling this dataset?


```
I have played this game extensively throughout my life so I understand how the economy functions,
but a viewer of this dataset, may be very confused on the terminology and what to do.

Given the potential complexity of the in-game economy, overfitting.
```

Second Choice: **Car Insurance Data**

In [ ]:
# Save the filepath and load the data as df
fpath = "/content/drive/MyDrive/Colab Notebooks/PROJECT 2 [--]/Car_Insurance_Claim.csv"
df2 = pd.read_csv(fpath)
df2.head()

,ID,AGE,GENDER,RACE,DRIVING_EXPERIENCE,EDUCATION,INCOME,CREDIT_SCORE,VEHICLE_OWNERSHIP,VEHICLE_YEAR,MARRIED,CHILDREN,POSTAL_CODE,ANNUAL_MILEAGE,VEHICLE_TYPE,SPEEDING_VIOLATIONS,DUIS,PAST_ACCIDENTS,OUTCOME
0,569520,65+,female,majority,0-9y,high school,upper class,0.629027,1.0,after 2015,0.0,1.0,10238,12000.0,sedan,0,0,0,0.0
1,750365,16-25,male,majority,0-9y,none,poverty,0.357757,0.0,before 2015,0.0,0.0,10238,16000.0,sedan,0,0,0,1.0
2,199901,16-25,female,majority,0-9y,high school,working class,0.493146,1.0,before 2015,0.0,0.0,10238,11000.0,sedan,0,0,0,0.0
3,478866,16-25,male,majority,0-9y,university,working class,0.206013,1.0,before 2015,0.0,1.0,32765,11000.0,sedan,0,0,0,0.0
4,731664,26-39,male,majority,10-19y,none,working class,0.388366,1.0,before 2015,0.0,0.0,32765,12000.0,sedan,2,0,1,1.0

In [ ]:
# Get the shape of the dataset (rows, columns)
num_rows, num_columns = df2.shape

# Get the column names
column_names = df2.columns.tolist()

print("Number of features (columns):", num_columns)
print("Column names:", column_names)

Number of features (columns): 9
Column names: ['League', 'Date', 'Get', 'Pay', 'Value', 'Confidence', 'Patch', 'Hardcore', 'Standard']

In [ ]:
# Get the shape of the dataset (rows, columns)
num_rows, num_columns = df2.shape

print("Number of rows:", num_rows)

Number of rows: 24649

1. Source of data

[Kaggle](https://www.kaggle.com/datasets/sagnik1511/car-insurance-data)
```
[Kaggle]
```


2. Brief description of data


```
The columns are resembling practical world features.
The outcome column indicates 1 if a customer has claimed his/her loan else 0.
The data has 19 features from there 18 of them are corresponding logs which were taken by the company.
```


3. What is the target?


```
The goal is to predict whether a customer will claim their car insurance (1) or not (0)
```


4. What does one row represent? (A person? A business? An event? A product?)


```
A person
```


5. Is this a classification or regression problem?


```
classification problem
```


6. How many features does the data have?


```
9
```


7. How many rows are in the dataset?


```
24649
```


8. What, if any, challenges do you foresee in cleaning, exploring, or modeling this dataset?


```
EDA.
Understanding the relationships between features, their distributions, and potential correlations with the outcome variable is crucial.
EDA can reveal insights that guide the feature selection process and help in identifying potential outliers or anomalies that need to be handled.
```